import { useState } from 'react';
import { Box, CheckCircle2, Circle, ExternalLink, Package, RefreshCw, Settings2, Terminal } from 'lucide-react';

export default function ManagementPage({ onToast, runtime, providerCount }: { onToast: (message: string) => void; runtime: { agentDir?: string; piPath?: string; skillsCount: number; extensionsCount: number }; providerCount: number }) {
  const [tab, setTab] = useState<'pi' | 'plugins'>('pi');
  return (
    <div className="flex min-h-0 flex-1 flex-col bg-[var(--bg-main)]">
      <div className="flex h-[52px] shrink-0 items-center border-b border-[var(--border)] px-6"><h1 className="text-[15px] font-semibold text-[var(--text)]">Pi 管理与插件</h1><div className="flex-1" /><button onClick={() => onToast('正在刷新 Pi 状态')} className="flex h-8 w-8 items-center justify-center rounded-lg text-[var(--text-2)] hover:bg-[var(--bg-hover)]"><RefreshCw size={15} /></button></div>
      <div className="flex gap-1 border-b border-[var(--border)] px-6 pt-3"><button onClick={() => setTab('pi')} className={`rounded-t-lg px-3 py-2 text-[13px] ${tab === 'pi' ? 'bg-[var(--bg-active)] text-[var(--text)]' : 'text-[var(--text-2)]'}`}>Pi 管理</button><button onClick={() => setTab('plugins')} className={`rounded-t-lg px-3 py-2 text-[13px] ${tab === 'plugins' ? 'bg-[var(--bg-active)] text-[var(--text)]' : 'text-[var(--text-2)]'}`}>插件管理</button></div>
      <div className="scroll-thin flex-1 overflow-y-auto p-6"><div className="mx-auto max-w-[760px] space-y-3">
        {tab === 'pi' ? <>
          <section className="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-4"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--bg-hover)] text-[var(--text)]"><Terminal size={18} /></div><div className="flex-1"><div className="flex items-center gap-2 font-medium text-[var(--text)]">Pi Agent <span className="flex items-center gap-1 text-[11px] font-normal text-[#3fb950]"><CheckCircle2 size={12} />已连接 Pi 配置</span></div><p className="mt-1 break-all text-[12.5px] text-[var(--text-3)]">{runtime.piPath || '未找到 Pi 可执行文件'}<br />{runtime.agentDir || '未找到 Pi 配置目录'}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-[12px]"><div className="rounded-lg bg-[var(--bg-hover)] p-3"><div className="text-[var(--text-3)]">运行模式</div><div className="mt-1 text-[var(--text)]">RPC 会话</div></div><div className="rounded-lg bg-[var(--bg-hover)] p-3"><div className="text-[var(--text-3)]">Provider</div><div className="mt-1 text-[var(--text)]">{providerCount}</div></div></div><button onClick={() => onToast('Pi 配置文件已由 WEPI 直接读写')} className="mt-3 flex items-center gap-2 rounded-lg border border-[var(--border-strong)] px-3 py-2 text-[13px] text-[var(--text)] hover:bg-[var(--bg-hover)]"><Settings2 size={14} />配置文件位置</button></section>
          <section className="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-4"><div className="flex items-center gap-2 font-medium text-[var(--text)]"><Package size={16} /> Pi 资源</div><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-lg bg-[var(--bg-hover)] p-3"><div className="text-[var(--text-3)]">Providers</div><div className="mt-1 text-[18px] text-[var(--text)]">{providerCount}</div></div><div className="rounded-lg bg-[var(--bg-hover)] p-3"><div className="text-[var(--text-3)]">Skills</div><div className="mt-1 text-[18px] text-[var(--text)]">{runtime.skillsCount}</div></div><div className="rounded-lg bg-[var(--bg-hover)] p-3"><div className="text-[var(--text-3)]">Extensions</div><div className="mt-1 text-[18px] text-[var(--text)]">{runtime.extensionsCount}</div></div></div></section>
        </> : <>
          {['内置工具与 MCP', 'Skill 扩展', '项目扩展'].map((name, index) => <div key={name} className="flex items-center gap-3 rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-4"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[var(--bg-hover)] text-[var(--text-2)]"><Box size={16} /></div><div className="flex-1"><div className="text-[13.5px] text-[var(--text)]">{name}</div><div className="mt-1 text-[12px] text-[var(--text-3)]">由 Pi 资源加载器发现并管理</div></div>{index < 2 ? <CheckCircle2 size={15} className="text-[#3fb950]" /> : <Circle size={15} className="text-[var(--text-3)]" />}</div>)}
          <button onClick={() => onToast('插件管理将复用 Pi 的 extensions / skills / MCP 配置')} className="flex items-center gap-2 text-[12.5px] text-[var(--text-3)] hover:text-[var(--text)]"><ExternalLink size={13} />查看 Pi 插件文档</button>
        </>}
      </div></div>
    </div>
  );
}
